import { Router } from 'express';
import { createRequest, claimRequest, findRequestById, listRequests, updateRequestStatus } from '../database/repository.js';
import { fail, ok, requireAuth, requireRole, type AuthenticatedRequest } from '../middleware/http.js';
import { validate } from '../middleware/validate.js';
import { listSchema, requestSchema, statusSchema } from '../validators/index.js';
import type { RequestStatus } from '../types.js';

export const requestsRouter = Router();
requestsRouter.use(requireAuth);
requestsRouter.get('/', validate(listSchema, 'query'), async (req, res, next) => { try { const result = await listRequests(req.query as never); return ok(res, result); } catch (error) { next(error); } });
requestsRouter.get('/nearby', validate(listSchema, 'query'), async (req, res, next) => { try { const result = await listRequests(req.query as never); return ok(res, result); } catch (error) { next(error); } });
requestsRouter.post('/', validate(requestSchema), async (req: AuthenticatedRequest, res, next) => { try { const user = req.user!; const input = req.body; const request = await createRequest({ ...input, requesterId: user.id, requesterName: user.name, status: 'OPEN' }); req.app.get('io')?.emit('request:new', request); return ok(res, request, 201); } catch (error) { next(error); } });
requestsRouter.post('/:id/accept', requireRole('VOLUNTEER', 'ADMIN'), async (req: AuthenticatedRequest, res, next) => { try { const request = await claimRequest(String(req.params.id), req.user!); if (!request) return fail(res, 'REQUEST_UNAVAILABLE', 'This request has already been claimed or is no longer open.', 409); req.app.get('io')?.emit('request:accepted', request); return ok(res, request); } catch (error) { next(error); } });
requestsRouter.patch('/:id/status', validate(statusSchema), async (req: AuthenticatedRequest, res, next) => { try { const status = req.body.status as RequestStatus; const id = String(req.params.id); const existing = await findRequestById(id); if (!existing) return fail(res, 'NOT_FOUND', 'Request not found.', 404); if (req.user?.role === 'CITIZEN' && !(status === 'CANCELLED' && existing.requesterId === req.user.id)) return fail(res, 'FORBIDDEN', 'Only the requester can cancel this request.', 403); if (req.user?.role === 'VOLUNTEER' && existing.assignedVolunteerId !== req.user.id) return fail(res, 'FORBIDDEN', 'Only the assigned volunteer can update response progress.', 403); const transitions: Record<RequestStatus, RequestStatus[]> = { OPEN: ['MATCHED', 'CANCELLED'], MATCHED: ['ACCEPTED', 'CANCELLED'], ACCEPTED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['RESOLVED', 'CANCELLED'], RESOLVED: [], CANCELLED: [] }; if (!transitions[existing.status].includes(status)) return fail(res, 'INVALID_STATUS', `Cannot move a ${existing.status} request to ${status}.`, 422); const request = await updateRequestStatus(id, status); req.app.get('io')?.emit(status === 'RESOLVED' ? 'request:resolved' : 'request:updated', request); return ok(res, request); } catch (error) { next(error); } });
