import { ArrowUpRight, ClipboardList, Clock3, FileWarning, LifeBuoy, Package } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Badge, PageHeader, timeAgo } from '../components/ui';

export function ActivityPage() {
  const { user, requests, offers, hazards } = useApp();
  const myRequests = requests.filter((item) => item.requester.id === user?.id || item.assignedVolunteer?.id === user?.id);
  const myOffers = offers.filter((item) => item.owner.id === user?.id);
  const myHazards = hazards.filter((item) => item.reporter.id === user?.id);
  return <div className="page-stack"><PageHeader eyebrow="Your contribution" title="My activity" description="A private view of the requests, offers, and reports connected to your account." /><div className="activity-stats"><div><LifeBuoy size={17} /><strong>{myRequests.length}</strong><span>requests involved</span></div><div><Package size={17} /><strong>{myOffers.length}</strong><span>offers shared</span></div><div><FileWarning size={17} /><strong>{myHazards.length}</strong><span>hazards reported</span></div></div><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Recent timeline</span><h2>Your activity</h2></div></div><div className="timeline">{[...myRequests.map((request) => ({ id: request.id, icon: LifeBuoy, title: request.title, description: `Request is ${request.status.toLowerCase().replace('_', ' ')}${request.assignedVolunteer ? ` · Responding: ${request.assignedVolunteer.name}` : ''}`, date: request.updatedAt, badge: request.status })), ...myOffers.map((offer) => ({ id: offer.id, icon: Package, title: offer.description, description: `Offer shared near ${offer.locationLabel}`, date: offer.createdAt, badge: offer.status })), ...myHazards.map((hazard) => ({ id: hazard.id, icon: FileWarning, title: hazard.locationLabel, description: `Hazard report · ${hazard.verification.toLowerCase().replace('_', ' ')}`, date: hazard.createdAt, badge: hazard.severity }))].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).map((item) => <div className="timeline-item" key={item.id}><span className="timeline-icon"><item.icon size={16} /></span><div><div className="timeline-title"><strong>{item.title}</strong><Badge value={item.badge} /></div><p>{item.description}</p><span className="timeline-time"><Clock3 size={13} />{timeAgo(item.date)}</span></div><ArrowUpRight size={16} className="timeline-arrow" /></div>)}{!myRequests.length && !myOffers.length && !myHazards.length && <div className="empty-activity"><ClipboardList size={20} /><p>Your activity will appear here as you participate.</p></div>}</div></section></div>;
}
