import { AlertCircle, BarChart3, CheckCircle2, FileWarning, ShieldCheck, UsersRound } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useApp } from '../context/AppContext';
import { AlertCard, Badge, Button, EmptyState, HazardCard, PageHeader } from '../components/ui';
import { Navigate, useNavigate } from 'react-router-dom';
import { apiService } from '../services/api';
import type { UserSummary } from '../types';

export function AdminDashboardPage() {
  const { user, requests, hazards, alerts, dashboardStats, isHydrating } = useApp(); const navigate = useNavigate(); if (user?.role !== 'ADMIN') return <Navigate to="/" replace />;
  return <div className="page-stack"><PageHeader eyebrow="Operations control" title="Admin dashboard" description="Monitor community activity, review reports, and keep the network trustworthy." action={<div className="admin-status"><ShieldCheck size={15} /> Admin mode</div>} /><div className="stats-grid admin-stats"><Stat value={dashboardStats.openRequests} label="Active requests" icon={AlertCircle} tone="red" loading={isHydrating} /><Stat value={hazards.filter((item) => item.verification === 'UNVERIFIED').length} label="Unverified hazards" icon={FileWarning} tone="amber" /><Stat value={hazards.filter((item) => item.verification.includes('VERIFIED')).length} label="Verified hazards" icon={CheckCircle2} tone="green" /><Stat value={dashboardStats.volunteersAvailable} label="Active volunteers" icon={UsersRound} tone="blue" /></div><div className="admin-grid"><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Needs review</span><h2>Unverified hazards</h2></div><Button variant="ghost" size="sm" onClick={() => navigate('/admin/hazards')}>Review queue</Button></div>{hazards.filter((hazard) => hazard.verification === 'UNVERIFIED').slice(0, 3).map((hazard) => <HazardCard key={hazard.id} hazard={hazard} />)}{!hazards.some((hazard) => hazard.verification === 'UNVERIFIED') && <EmptyState icon={CheckCircle2} title="Queue is clear" description="All recent hazard reports have been reviewed." />}</section><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Broadcasts</span><h2>Latest alerts</h2></div><Button variant="secondary" size="sm" onClick={() => navigate('/alerts')}>Create alert</Button></div>{alerts.slice(0, 3).map((alert) => <AlertCard key={alert.id} alert={alert} compact />)}</section></div><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Operational overview</span><h2>Recent critical requests</h2></div><BarChart3 size={19} className="muted-icon" /></div><div className="admin-table"><div className="table-row table-head"><span>Request</span><span>Area</span><span>Urgency</span><span>Status</span></div>{requests.filter((item) => item.urgency === 'CRITICAL').map((request) => <div className="table-row" key={request.id}><strong>{request.title}</strong><span>{request.locationLabel}</span><Badge value={request.urgency} /><Badge value={request.status} /></div>)}</div></section></div>;
}

function Stat({ value, label, icon: Icon, tone, loading = false }: { value: number; label: string; icon: typeof AlertCircle; tone: string; loading?: boolean }) { return <div className="stat-card-new"><div className={`stat-icon stat-${tone}`}><Icon size={18} /></div><div className="stat-content"><span className="stat-label">{label}</span><strong>{loading ? '—' : value}</strong><span className="stat-detail">{loading ? 'Updating…' : 'Live data'}</span></div></div>; }

export function AdminHazardsPage() {
  const { user, hazards, moderateHazard } = useApp(); if (user?.role !== 'ADMIN') return <Navigate to="/" replace />;
  return <div className="page-stack"><PageHeader eyebrow="Administration" title="Hazard verification" description="Review community reports before they become part of the trusted operational picture." /><div className="verification-header"><div><strong>{hazards.filter((hazard) => hazard.verification === 'UNVERIFIED').length} reports waiting</strong><span>Community confirmations are signals, not official government verification.</span></div><Badge value="Admin review required" /></div><div className="list-grid">{hazards.filter((hazard) => hazard.verification === 'UNVERIFIED').map((hazard) => <article className="review-card" key={hazard.id}><HazardCard hazard={hazard} /><div className="review-actions"><Button size="sm" variant="success" onClick={() => void moderateHazard(hazard.id, 'ADMIN_VERIFIED')}>Verify report</Button><Button size="sm" variant="secondary" onClick={() => void moderateHazard(hazard.id, 'REJECTED')}>Reject</Button></div></article>)}</div></div>;
}

export function AdminUsersPage() {
  const { user } = useApp(); const [users, setUsers] = useState<UserSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadUsers = useCallback(async () => { setLoading(true); setError(null); try { const result = await apiService.adminUsers({ page: 1, limit: 50 }); setUsers(result.items); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load workspace users.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void loadUsers(); }, [loadUsers]);
  if (user?.role !== 'ADMIN') return <Navigate to="/" replace />;
  return <div className="page-stack"><PageHeader eyebrow="Administration" title="User management" description="Review roles and participation status for the RescueLink workspace." /><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">{users.length} members</span><h2>Workspace users</h2></div><Button variant="secondary" size="sm"><UsersRound size={15} /> Invite volunteer</Button></div>{error && <div className="page-notice error"><AlertCircle size={17} /><span>{error}</span><Button variant="secondary" size="sm" onClick={() => void loadUsers()}>Try again</Button></div>}{loading ? <p className="section-subtitle">Loading workspace users…</p> : <div className="admin-table"><div className="table-row table-head"><span>Member</span><span>Role</span><span>Status</span><span>Action</span></div>{users.map((member) => <div className="table-row" key={member.email}><div className="member-cell"><span className="avatar small">{member.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><span><strong>{member.name}</strong><small>{member.email}</small></span></div><Badge value={member.role} /><Badge value={member.isAvailable ? 'Active' : 'Unavailable'} /><button className="text-button">Manage</button></div>)}</div>}</section></div>;
}
