import { Bell, CheckCheck, Info, Plus, ShieldAlert } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useApp } from '../context/AppContext';
import { AlertCard, Badge, Button, EmptyState, Modal, PageHeader } from '../components/ui';
import type { AlertSeverity, CreateAlertInput } from '../types';

export function AlertsPage() {
  const { user, alerts, notifications, markNotificationRead, createAlert } = useApp(); const [open, setOpen] = useState(false);
  const unread = notifications.filter((item) => !item.read);
  return <div className="page-stack"><PageHeader eyebrow="Stay informed" title="Alert center" description="Official alerts and relevant community updates for your current area." action={user?.role === 'ADMIN' ? <Button onClick={() => setOpen(true)}><Plus size={16} />Create alert</Button> : <div className="alert-sync"><span className="status-dot live" /> Real-time updates</div>} /><div className="alerts-layout"><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Emergency notices</span><h2>Active alerts</h2></div><Badge value={`${alerts.length} active`} /></div><div className="alert-list">{alerts.map((alert) => <AlertCard key={alert.id} alert={alert} />)}</div></section><section className="content-card notifications-panel"><div className="section-title-row"><div><span className="eyebrow">For you</span><h2>Notifications</h2></div><Button variant="ghost" size="sm" onClick={() => unread.forEach((notification) => markNotificationRead(notification.id))}><CheckCheck size={15} /> Mark all read</Button></div>{unread.length ? unread.map((notification) => <button className="notification-item" key={notification.id} onClick={() => markNotificationRead(notification.id)}><span className={`notification-icon ${notification.type.toLowerCase()}`}>{notification.type === 'HAZARD' ? <ShieldAlert size={16} /> : notification.type === 'ALERT' ? <Bell size={16} /> : <Info size={16} />}</span><span><strong>{notification.title}</strong><small>{notification.description}</small><em>New update</em></span></button>) : <EmptyState icon={CheckCheck} title="You're all caught up" description="Unread updates about your requests and nearby activity will appear here." />}</section></div><AlertForm open={open} onClose={() => setOpen(false)} onSubmit={async (input) => { await createAlert(input); setOpen(false); }} /></div>;
}

function AlertForm({ open, onClose, onSubmit }: { open: boolean; onClose: () => void; onSubmit: (input: CreateAlertInput) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [severity, setSeverity] = useState<AlertSeverity>('HIGH'); const [area, setArea] = useState(''); const [radiusKm, setRadiusKm] = useState(5); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (description.trim().length < 10) { setError('Add enough detail for people to understand the alert.'); return; } setSubmitting(true); setError(''); try { await onSubmit({ title: title.trim(), description: description.trim(), severity, area: area.trim(), radiusKm }); } catch { setError('Could not create the alert.'); } finally { setSubmitting(false); } };
  return <Modal open={open} onClose={onClose} title="Create emergency alert" description="Admin alerts are broadcast to the current community workspace."><form className="modal-form" onSubmit={submit}><label className="field-label">Alert title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Avoid low-lying roads near the river" required /></label><label className="field-label">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Share the clearest verified guidance available." required /></label><div className="form-grid"><label className="field-label">Severity<select value={severity} onChange={(event) => setSeverity(event.target.value as AlertSeverity)}>{['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field-label">Affected radius<input type="number" min={1} max={100} value={radiusKm} onChange={(event) => setRadiusKm(Number(event.target.value))} /></label></div><label className="field-label">Area or landmark<input value={area} onChange={(event) => setArea(event.target.value)} placeholder="e.g. Adyar river basin" required /></label>{error && <p className="field-error">{error}</p>}<div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" variant="danger" disabled={submitting}>{submitting ? 'Broadcasting…' : 'Broadcast alert'}</Button></div></form></Modal>;
}
