import { useState, type FormEvent } from 'react';
import { FileWarning, MapPin, Plus } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Button, EmptyState, HazardCard, Modal, PageHeader } from '../components/ui';
import type { AlertSeverity, CreateHazardInput, HazardType } from '../types';

const hazardTypes: HazardType[] = ['FLOOD', 'FIRE', 'ROAD_BLOCK', 'POWER_LINE', 'DEBRIS', 'BUILDING_DAMAGE', 'OTHER'];
const severities: AlertSeverity[] = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

export function HazardsPage() {
  const { hazards, createHazard, voteHazard } = useApp(); const [open, setOpen] = useState(false); const [filter, setFilter] = useState('ALL');
  const filtered = filter === 'ALL' ? hazards : hazards.filter((hazard) => hazard.severity === filter || hazard.verification === filter);
  return <div className="page-stack"><PageHeader eyebrow="Community safety" title="Hazard reports" description="Help the neighborhood understand what is unsafe right now." action={<Button variant="danger" onClick={() => setOpen(true)}><Plus size={17} />Report a hazard</Button>} /><div className="hazard-notice"><div className="notice-icon"><MapPin size={17} /></div><div><strong>Community reports are not official emergency instructions.</strong><p>Use your judgment, keep a safe distance, and contact emergency services when there is immediate danger.</p></div></div><div className="filter-pills hazard-filters"><button className={filter === 'ALL' ? 'active' : ''} onClick={() => setFilter('ALL')}>All reports</button>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'COMMUNITY_VERIFIED'].map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item.replace('_', ' ')}</button>)}</div><div className="list-grid">{filtered.length ? filtered.map((hazard) => <HazardCard key={hazard.id} hazard={hazard} canVote onVote={(vote) => voteHazard(hazard.id, vote)} />) : <EmptyState icon={FileWarning} title="No nearby hazards" description="There are no reports matching this filter. New community reports will appear here." />}</div><HazardForm open={open} onClose={() => setOpen(false)} onSubmit={async (input) => { await createHazard(input); setOpen(false); }} /></div>;
}

function HazardForm({ open, onClose, onSubmit }: { open: boolean; onClose: () => void; onSubmit: (input: CreateHazardInput) => Promise<void> }) {
  const [type, setType] = useState<HazardType>('FLOOD'); const [severity, setSeverity] = useState<AlertSeverity>('MEDIUM'); const [location, setLocation] = useState(''); const [description, setDescription] = useState(''); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (description.trim().length < 15) { setError('Please describe the hazard in enough detail for others to stay safe.'); return; } setSubmitting(true); setError(''); try { await onSubmit({ type, severity, locationLabel: location.trim(), description: description.trim(), lat: 13.0012, lng: 80.2565 }); } catch { setError('Could not submit the report. Please try again.'); } finally { setSubmitting(false); } };
  return <Modal open={open} onClose={onClose} title="Report a hazard" description="Reports start as unverified and can be confirmed by nearby community members."><form className="modal-form" onSubmit={submit}><div className="form-grid"><label className="field-label">Hazard type<select value={type} onChange={(event) => setType(event.target.value as HazardType)}>{hazardTypes.map((item) => <option key={item}>{item.replace('_', ' ')}</option>)}</select></label><label className="field-label">Severity<select value={severity} onChange={(event) => setSeverity(event.target.value as AlertSeverity)}>{severities.map((item) => <option key={item}>{item}</option>)}</select></label></div><label className="field-label">Location or landmark<input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="e.g. LB Road near the bus stop" required /></label><label className="field-label">What did you observe?<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Include what is blocked, who may be at risk, and whether it is still active." required /></label>{error && <p className="field-error">{error}</p>}<div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" variant="danger" disabled={submitting}>{submitting ? 'Submitting…' : 'Submit report'}</Button></div></form></Modal>;
}
