import { useMemo, useState } from 'react';
import { Layers3, MapPin, RotateCcw } from 'lucide-react';
import { MapView } from '../components/MapView';
import { Button, PageHeader } from '../components/ui';
import { useApp } from '../context/AppContext';

export function LiveMapPage() {
  const { requests, offers, hazards, liveLocations, retryHydration } = useApp(); const [showRequests, setShowRequests] = useState(true); const [showOffers, setShowOffers] = useState(true); const [showHazards, setShowHazards] = useState(true); const [radius, setRadius] = useState('10');
  const visibleRequests = useMemo(() => showRequests ? requests.filter((request) => request.distanceKm <= Number(radius) || request.distanceKm === 0) : [], [radius, requests, showRequests]);
  const visibleOffers = useMemo(() => showOffers ? offers.filter((offer) => offer.distanceKm <= Number(radius) || offer.distanceKm === 0) : [], [offers, radius, showOffers]);
  const visibleHazards = useMemo(() => showHazards ? hazards.filter((hazard) => hazard.distanceKm <= Number(radius) || hazard.distanceKm === 0) : [], [hazards, radius, showHazards]);
  return <div className="page-stack map-page"><PageHeader eyebrow="Live situational awareness" title="Emergency map" description="Explore nearby activity. Exact live locations are only shown when a person has explicitly enabled sharing." action={<div className="map-live-status"><span className="status-dot live" /> Updated just now <Button variant="ghost" size="sm" onClick={retryHydration}><RotateCcw size={14} /> Refresh</Button></div>} /><div className="map-controls"><label><span>Search radius</span><select value={radius} onChange={(event) => setRadius(event.target.value)}><option value="5">5 km</option><option value="10">10 km</option><option value="20">20 km</option></select></label><div className="map-toggles"><button className={showRequests ? 'on requests' : ''} onClick={() => setShowRequests((value) => !value)}><i />Requests</button><button className={showOffers ? 'on offers' : ''} onClick={() => setShowOffers((value) => !value)}><i />Resources</button><button className={showHazards ? 'on hazards' : ''} onClick={() => setShowHazards((value) => !value)}><i />Hazards</button></div><span className="map-count"><Layers3 size={15} />{visibleRequests.length + visibleOffers.length + visibleHazards.length + liveLocations.length} signals in view</span></div><div className="full-map-card"><MapView full requests={visibleRequests} offers={visibleOffers} hazards={visibleHazards} liveLocations={liveLocations} /><div className="map-bottom-note"><MapPin size={15} />Blue area indicates your approximate neighborhood. No exact location is shared unless you start live sharing.</div></div><div className="map-summary"><div><strong>{visibleRequests.length}</strong><span>open requests</span></div><div><strong>{visibleOffers.length}</strong><span>resources nearby</span></div><div><strong>{visibleHazards.length}</strong><span>hazards reported</span></div><div><strong>{liveLocations.length}</strong><span>live locations shared</span></div></div></div>;
}
