import { useMemo, useState, type FormEvent } from 'react';
import { Package, Plus, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Button, EmptyState, Modal, OfferCard, PageHeader } from '../components/ui';
import type { Category, CreateOfferInput } from '../types';

const categories: Category[] = ['FOOD', 'WATER', 'SHELTER', 'TRANSPORT', 'MEDICAL', 'SUPPLIES', 'RESCUE', 'OTHER'];

export function OffersPage() {
  const { user, offers, createOffer } = useApp(); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false);
  const filtered = useMemo(() => offers.filter((offer) => `${offer.description} ${offer.category} ${offer.locationLabel}`.toLowerCase().includes(search.toLowerCase())), [offers, search]);
  return <div className="page-stack"><PageHeader eyebrow="Volunteer network" title="Resource offers" description="See what your neighbors can share and make your own capacity visible." action={user?.role === 'CITIZEN' ? <Button variant="secondary" onClick={() => setOpen(true)}><Plus size={17} />Become a resource</Button> : <Button variant="success" onClick={() => setOpen(true)}><Plus size={17} />Add an offer</Button>} /><div className="toolbar"><div className="search-control"><Search size={16} /><input placeholder="Search resources or areas" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="toolbar-note"><span className="status-dot live" /> Offers are visible to nearby responders</div></div><div className="list-grid">{filtered.length ? filtered.map((offer) => <OfferCard key={offer.id} offer={offer} />) : <EmptyState icon={Package} title="No offers found" description="When volunteers share food, shelter, transport, or supplies, their capacity will appear here." />}</div><OfferForm open={open} onClose={() => setOpen(false)} onSubmit={async (input) => { await createOffer(input); setOpen(false); }} /></div>;
}

function OfferForm({ open, onClose, onSubmit }: { open: boolean; onClose: () => void; onSubmit: (input: CreateOfferInput) => Promise<void> }) {
  const [category, setCategory] = useState<Category>('FOOD'); const [description, setDescription] = useState(''); const [quantity, setQuantity] = useState(''); const [radiusKm, setRadiusKm] = useState(5); const [location, setLocation] = useState('Adyar, Chennai'); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (description.trim().length < 12 || !quantity.trim()) { setError('Add a clear description and available capacity.'); return; } setSubmitting(true); setError(''); try { await onSubmit({ category, description: description.trim(), quantity: quantity.trim(), radiusKm, locationLabel: location.trim(), lat: 13.0012, lng: 80.2565 }); } catch { setError('Could not save the offer. Please try again.'); } finally { setSubmitting(false); } };
  return <Modal open={open} onClose={onClose} title="Share a resource" description="Your offer will be matched with requests within the radius you choose."><form className="modal-form" onSubmit={submit}><div className="form-grid"><label className="field-label">Resource type<select value={category} onChange={(event) => setCategory(event.target.value as Category)}>{categories.map((item) => <option key={item}>{item.replace('_', ' ')}</option>)}</select></label><label className="field-label">Available capacity<input value={quantity} onChange={(event) => setQuantity(event.target.value)} placeholder="e.g. 20 meals or 4 seats" required /></label></div><label className="field-label">What can you provide?<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what is ready and any conditions for pickup or delivery." required /></label><div className="form-grid"><label className="field-label">Available around<input value={location} onChange={(event) => setLocation(event.target.value)} required /></label><label className="field-label">Response radius<select value={radiusKm} onChange={(event) => setRadiusKm(Number(event.target.value))}><option value={2}>2 km</option><option value={5}>5 km</option><option value={10}>10 km</option><option value={20}>20 km</option></select></label></div>{error && <p className="field-error">{error}</p>}<div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" variant="success" disabled={submitting}>{submitting ? 'Sharing…' : 'Publish offer'}</Button></div></form></Modal>;
}
