import { useState } from 'react';
import { Check, LockKeyhole, MapPin, ShieldCheck, UserRound } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Badge, Button, PageHeader } from '../components/ui';

export function ProfilePage() {
  const { user, showToast, startLiveLocation, stopLiveLocation } = useApp(); const [sharing, setSharing] = useState(false); const [available, setAvailable] = useState(user?.isAvailable ?? true);
  const toggleSharing = () => { if (sharing) { void stopLiveLocation(); setSharing(false); showToast('Live location sharing stopped.', 'info'); return; } if (!navigator.geolocation) { showToast('Location sharing is not available in this browser.', 'error'); return; } navigator.geolocation.getCurrentPosition(async (position) => { await startLiveLocation({ lat: position.coords.latitude, lng: position.coords.longitude, status: 'AVAILABLE_TO_RESPOND' }); setSharing(true); showToast('Live location sharing started for 10 minutes.', 'success'); }, () => showToast('Location permission was not granted. Your exact location stays private.', 'error'), { enableHighAccuracy: false, timeout: 8000 }); };
  return <div className="page-stack"><PageHeader eyebrow="Account settings" title="Profile & privacy" description="Manage how you participate in the RescueLink community." /><div className="profile-grid"><section className="content-card profile-card"><div className="profile-identity"><span className="profile-avatar-large">{user?.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><div><h2>{user?.name}</h2><p>{user?.email}</p><Badge value={user?.role || 'CITIZEN'} /></div></div><div className="profile-divider" /><div className="profile-fields"><label className="field-label">Display name<input value={user?.name || ''} readOnly /></label><label className="field-label">Home area<input value={user?.locationLabel || 'Adyar, Chennai'} readOnly /></label></div><Button variant="secondary" onClick={() => showToast('Profile editing will be available in the connected API.', 'info')}>Edit profile</Button></section><section className="content-card"><div className="section-title-row"><div><span className="eyebrow">Privacy controls</span><h2>Choose what to share</h2></div><ShieldCheck size={21} className="muted-icon" /></div><div className="setting-row"><span className="setting-icon"><MapPin size={17} /></span><div><strong>Temporary live location</strong><p>Share your exact location for 10 minutes so responders can find you. It automatically expires.</p></div><button className={`switch ${sharing ? 'on' : ''}`} aria-label="Toggle live location sharing" onClick={toggleSharing}><span /></button></div><div className="setting-row"><span className="setting-icon green"><UserRound size={17} /></span><div><strong>Available to respond</strong><p>Let nearby requesters know when you can help. You can change this anytime.</p></div><button className={`switch ${available ? 'on' : ''}`} aria-label="Toggle volunteer availability" onClick={() => setAvailable((value) => !value)}><span /></button></div><div className="setting-row"><span className="setting-icon blue"><LockKeyhole size={17} /></span><div><strong>Contact preference</strong><p>Keep conversations in-app by default. Phone numbers are never shown publicly.</p></div><Check size={18} className="check-icon" /></div></section></div><section className="privacy-banner"><ShieldCheck size={19} /><div><strong>Privacy is a feature, not an afterthought.</strong><p>RescueLink uses your approximate area for matching. Exact live locations are temporary, permission-based, and shared only with relevant responders.</p></div></section></div>;
}
