import { useMemo, useState, type FormEvent } from 'react';
import { Filter, LifeBuoy, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Button, EmptyState, Modal, PageHeader, RequestCard } from '../components/ui';
import type { Category, CreateRequestInput, HelpRequest, Urgency } from '../types';
import { useSearchParams } from 'react-router-dom';

const categories: Category[] = ['MEDICAL', 'FOOD', 'WATER', 'SHELTER', 'TRANSPORT', 'RESCUE', 'SUPPLIES', 'OTHER'];
const urgencies: Urgency[] = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

export function RequestsPage() {
  const { user, requests, createRequest, acceptRequest, updateRequestStatus } = useApp();
  const [searchParams, setSearchParams] = useSearchParams();
  const [filter, setFilter] = useState('ALL'); const [search, setSearch] = useState(''); const [open, setOpen] = useState(() => searchParams.get('compose') === '1');
  const openComposer = () => { setOpen(true); const next = new URLSearchParams(searchParams); next.set('compose', '1'); setSearchParams(next, { replace: true }); };
  const closeComposer = () => { setOpen(false); if (searchParams.has('compose')) { const next = new URLSearchParams(searchParams); next.delete('compose'); setSearchParams(next, { replace: true }); } };
  const filtered = useMemo(() => requests.filter((request) => (filter === 'ALL' || request.status === filter || request.urgency === filter) && `${request.title} ${request.description} ${request.locationLabel}`.toLowerCase().includes(search.toLowerCase())), [filter, requests, search]);
  return <div className="page-stack"><PageHeader eyebrow="Community coordination" title="Help requests" description="Find open needs, respond with the right support, and track progress." action={<Button onClick={openComposer}><Plus size={17} />Request help</Button>} /><div className="toolbar"><div className="search-control"><Search size={16} /><input placeholder="Search requests or areas" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="filter-pills"><button className={filter === 'ALL' ? 'active' : ''} onClick={() => setFilter('ALL')}><SlidersHorizontal size={14} />All</button>{['OPEN', 'HIGH', 'CRITICAL', 'IN_PROGRESS', 'RESOLVED'].map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item.replace('_', ' ')}</button>)}</div><span className="result-count"><Filter size={14} />{filtered.length} results</span></div><div className="list-grid">{filtered.length ? filtered.map((request) => <RequestCard key={request.id} request={request} canAccept={user?.role !== 'CITIZEN'} onAccept={() => acceptRequest(request.id)} onStatus={(status) => updateRequestStatus(request.id, status)} />) : <EmptyState icon={LifeBuoy} title="No requests match" description="Try a different filter or search term. Nearby requests will appear here as the community shares them." />}</div><RequestForm open={open} onClose={closeComposer} onSubmit={async (input) => { await createRequest(input); closeComposer(); }} /></div>;
}

function RequestForm({ open, onClose, onSubmit }: { open: boolean; onClose: () => void; onSubmit: (input: CreateRequestInput) => Promise<void> }) {
  const [category, setCategory] = useState<Category>('MEDICAL'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [urgency, setUrgency] = useState<Urgency>('MEDIUM'); const [location, setLocation] = useState(''); const [people, setPeople] = useState(1); const [contactPreference, setContactPreference] = useState<HelpRequest['contactPreference']>('IN_APP'); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (description.trim().length < 20) { setError('Please give responders at least a little more detail (20 characters minimum).'); return; } setSubmitting(true); setError(''); try { await onSubmit({ category, title: title.trim(), description: description.trim(), urgency, locationLabel: location.trim() || 'Adyar, Chennai', lat: 13.0012, lng: 80.2565, peopleAffected: people, contactPreference }); } catch { setError('Could not save the request. Please try again.'); } finally { setSubmitting(false); } };
  return <Modal open={open} onClose={onClose} title="Request emergency help" description="Share only the details a nearby responder needs to act."><form className="modal-form" onSubmit={submit}><div className="form-grid"><label className="field-label">Category<select value={category} onChange={(event) => setCategory(event.target.value as Category)}>{categories.map((item) => <option key={item}>{item.replace('_', ' ')}</option>)}</select></label><label className="field-label">Urgency<select value={urgency} onChange={(event) => setUrgency(event.target.value as Urgency)}>{urgencies.map((item) => <option key={item}>{item}</option>)}</select></label></div><label className="field-label">Short title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Need transport for two people" required /></label><label className="field-label">What is happening?<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Explain what you need, any safety concerns, and how responders can help." required /></label><div className="form-grid"><label className="field-label">Area or landmark<input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="e.g. Besant Nagar near the library" required /></label><label className="field-label">People affected<input type="number" min={1} max={1000} value={people} onChange={(event) => setPeople(Number(event.target.value))} required /></label></div><label className="field-label">Preferred contact<select value={contactPreference} onChange={(event) => setContactPreference(event.target.value as HelpRequest['contactPreference'])}><option value="IN_APP">In-app messages only</option><option value="PHONE">Phone (shared with assigned volunteer)</option><option value="WHATSAPP">WhatsApp (shared with assigned volunteer)</option></select></label>{error && <p className="field-error">{error}</p>}<div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={submitting}>{submitting ? 'Posting…' : 'Post request'}</Button></div></form></Modal>;
}
